################################################################################
#   CONFIGURATIONS FOR SIMULATED DATA MODEL
################################################################################

# Experiment

experiment:
  n_iter: 1

  test_stat : [DATE,DETT]

  weights_model : Logistic_Regression

  X_ker: RBF

  Y_ker: RBF

  significance_level : 0.05


# DATASET
data:
  # Name of the generator
  generator: shift_data_simulation

  n_train_sample: 100

  n_test_sample: 100

  arguments: 
    mu: [0.2,0]
    sigma: ID
    noise: 0.1
  
  functions:
    g_0: f_0 
    g_1: f_0 
  