################################################################################
#   CONFIGURATIONS FOR SIMULATED DATA MODEL
# Run python wrapped_simulated_experiment.py --cfg=/Users/jakefawkes/Python/DR_distributional_test/config/wrapped_simulaton_cfg.yaml --o=sandbox/plot_for_robin
################################################################################

# Experiment

moving_param:
  beta_scalar: False
  n_train_sample: True
  n_test_sample: True
  values : [500,1000,1500]

experiment:
  n_iter: 84

  test_stat : [DATE,DETT]

  comparison_model : [TMLE,DML]

  ker_regress: [cme,zero]

  weights_model : LR

  X_ker: RBF

  Y_ker: RBF

  significance_level : 0.05

  n_bins: 40

  cme_reg: [0.000000001,0.0001,20]

  permute_weights: True
  
  KMM_weights: False

# DATASET
data:
  # Name of the generator
  generator: shift_data_simulation
  
  dx: 10
  
  dy: 1

  n_train_sample: 500

  n_test_sample: 500

  arguments: 
    mu: [0,0,0,0,0,0,0,0,0,0]
    sigma: [C_ID,1.5]
    noise: 0.2
  
  functions:
    g_0: f_0
    g_1: f_1

# DATASET
# data:  
#     # Name of the generator
#   generator: linear_data_simulation

#   n_train_sample: 500

#   n_test_sample: 500
  
#   dx: 5
  
#   dy: 1
#   arguments: 
#     alpha_vec: [0.1,0.2,0.3,0.4,0.5]
#     beta_vec: [0.1,0.2,0.3,0.4,0.5]
#     beta_scalar: 0.2
#     effect_var: Const
#     noise_Y: 0.2

