################################################################################
#   CONFIGURATIONS FOR SIMULATED DATA MODEL
# Run python wrapped_simulated_experiment.py --cfg=/Users/jakefawkes/Python/DR_distributional_test/config/wrapped_simulaton_cfg.yaml --o=sandbox/
################################################################################

# Experiment

moving_param:
  beta_scalar: True
  n_train_sample: False
  n_test_sample: False
  values : [0,0.05,0.15,0.3,0.4]
experiment:

  n_iter: 100

  test_stat : [DATE]

  comparison_model : []

  ker_regress: [cme]

  weights_model : LR

  X_ker: RBF

  Y_ker: RBF

  significance_level : 0.05

  n_bins: 100

  n_train_perm: [1,5,10]

  cme_reg: 0.001

  permute_weights: true
  
  KMM_weights: False

  seed: 25


# data:
#   # Name of the generator
#   generator: shift_data_simulation
  
#   dx: 10
  
#   dy: 1

#   n_train_sample: 500

#   n_test_sample: 500

#   arguments: 
#     mu: [0,0,0,0,0,0,0,0,0,0]
#     sigma: [C_ID,1.3]
#     noise: 0.2
  
#   functions:
#     g_0: f_0
#     g_1: f_1

# DATASET
data:  
    # Name of the generator
  generator: linear_data_simulation

  n_train_sample: 1000

  n_test_sample: 1000
  
  dx: 9
  
  dy: 1
  arguments: 
    alpha_vec: [0.1,0.2,0.3,0.4,0.5,0.1,0.2,0.3,0.4]
    beta_vec: [0.5,0.4,0.3,0.2,0.1,0.4,0.3,0.2,0.1]
    beta_scalar: 0
    effect_var: Const
    noise_Y: 0.2

