################################################################################
#   CONFIGURATIONS FOR SIMULATED DATA MODEL
# Run python wrapped_simulated_experiment.py --cfg=/Users/jakefawkes/Python/DR_distributional_test/config/wrapped_simulaton_cfg.yaml --o=sandbox/
################################################################################

# Experiment

moving_param:
  beta_scalar: True
  n_train_sample: False
  n_test_sample: False
  values : [0]

experiment:
  n_iter: 2

  test_stat : [DATE,DETT]

  comparison_model : [TMLE,DML]

  ker_regress: [cme,zero]

  weights_model : MLP

  X_ker: RBF

  Y_ker: RBF

  significance_level : 0.05

  n_bins: 20

  cme_reg: [0.0001,0.1,20]

  permute_weights: True
  
  KMM_weights: True

# DATASET
# data:
#   # Name of the generator
#   generator: shift_data_simulation

#   n_train_sample: 200

#   n_test_sample: 200

#   arguments: 
#     mu: [0.1,0.1,0.1]
#     sigma: [C_ID,1.5]
#     noise: 0.2
  
#   functions:
#     g_0: f_0
#     g_1: f_0

# DATASET
data:  
    # Name of the generator
  generator: linear_data_simulation

  n_train_sample: 50

  n_test_sample: 50
  
  dx: 5
  
  dy: 1
  arguments: 
    alpha_vec: [0.1,0.2,0.3,0.4,0.5]
    beta_vec: [0.1,0.2,0.3,0.4,0.5]
    beta_scalar: 0.2
    effect_var: Unif
    noise_Y: 0.2

